services:
  db:
    image: mysql:8.0.27
    container_name: anomaly_detection_playground
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
